### ISSUE TITLE
TypeError: singleton can't be dumped

### ISSUE THREAD

**Issue by splattael** [tcopeland/pippi#22]
Hi,

first of all: Thanks for this library :)

While trying `pippi` on one of our projects I discovered several `TypeError`s after activating `pippi` in tests.

A simple reproduction:

```ruby
require 'bundler/setup'
require 'minitest/autorun'
require 'pippi'

Pippi::AutoRunner.new(:checkset => ENV['PIPPI_CHECKSET'] || "basic")

class MarshalDumpTest < Minitest::Test
  def test_dump_broken
    Marshal.dump([].select(&:odd?))
  end

  def test_dump_works
    Marshal.dump([].select(&:odd?).dup)
  end
end
```

### Output

```
Run options: --seed 39192

# Running:

E.

Finished in 0.002342s, 853.9608 runs/s, 0.0000 assertions/s.

  1) Error:
MarshalDumpTest#test_dump_broken:
TypeError: singleton can't be dumped
    test/marshal_dump_test.rb:9:in `dump'
    test/marshal_dump_test.rb:9:in `test_dump_broken'

2 runs, 0 assertions, 0 failures, 1 errors, 0 skips
```

Any pointers how to solve this issue?

**Comment by splattael** [comment]
Mh, obviously I didn't manage to fix this. Sorry for that :-(

**Comment by tcopeland** [comment]
No worries @splattael !   

I have to say, this project has not turned out to be as productive as I thought... the interprocedural checks haven't been as effective as I thought they'd be; too many false positives.  Still, I should revisit this and see if I can come up with a few more checks.
