### ISSUE TITLE
pippi 0.0.11 causing numerous rspec failures

### ISSUE THREAD

**Issue by dankohn** [tcopeland/pippi#26]
I've been using pippi 0.0.6 with no problems, but 0.0.11 is causing numerous RSpec failures. Frustratingly, the error is only on my CircleCI server (running Ubuntu), but not on my OS X dev machine, making it hard to diagnose the problem. It appears, though, that pippi is grabbing tons of memory when CircleCI has a 4 GB limit. I have:
```ruby
# spec/spec_helper.rb
if ENV['USE_PIPPI'].present?
  require 'pippi'
  Pippi::AutoRunner.new(checkset: ENV['PIPPI_CHECKSET'] || 'basic')
end
```
I'm invoking RSpec with:
```bash
USE_PIPPI=1 bundle exec rspec --color --require spec_helper --format documentation spec
```

**Comment by tcopeland** [comment]
@dankohn hmmm interesting, I'm not seeing spec failures locally, but I can imagine that it uses tons of memory on large codebases, since it adds singleton methods to many objects.  I'm not sure if there's much that we can do about it, though.

**Comment by dankohn** [comment]
That's fine. I'll just run it intermittently on my dev machine rather than
including it in our continuous integration test runs.

--
Dan Kohn <mailto:dan@dankohn.com>
tel:+1-415-233-1000

**Comment by tcopeland** [comment]
Cool ok.
